version: '3.8'

services:
  frontend:
    image: parthibanktech3/student-management-frontend:latest
    container_name: sms-frontend
    ports:
      - "80:80"
    networks:
      - microservices-net
    restart: always

networks:
  microservices-net:
    external: true
